name: First Workflow

on: [workflow_dispatch]

jobs:
  downstream-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.run_number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/
