name: Release Gradle Plugin

on: [workflow_dispatch]

permissions:
  contents: write
  issues: write

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.cz.output.version }}
      VERSION_ENV: ${{ env.REVISION }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        id: cz
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
  version:
    runs-on: ubuntu-latest
    needs: determine-version
    steps:
      - run: |
          echo "${{ needs.determine-version.outputs.VERSION }}"
          echo "${{ needs.determine-version.outputs.VERSION_ENV }}"
      
 
