name: Release Gradle Plugin

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic_version.outputs.version }}
      previous_version: ${{ steps.semantic_version.outputs.previous_version }}
      version_type: ${{ steps.semantic_version.outputs.version_type }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Versioning
        id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0

  release:
    runs-on: ubuntu-latest
    needs: determine-version
    if: needs.determine-version.outputs.version_type != 'none'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: v${{ needs.determine-version.outputs.version }}
          toTag: v${{ needs.determine-version.outputs.previous_version }}
          writeToFile: false

      - name: Generate GitHub Release Notes
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: v${{ needs.determine-version.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
