name: Two

on:
 workflow_run:
   workflows: ["One"]
   types: 
     - completed

jobs:
  reusable:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.workflow_run.outputs.ONE }}"